### ISSUE TITLE
"Feature" pages/icons On Home Screen Easily Editable

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#13]
It would be nice to be able to easily add and subtract from the six feature pages on the homescreen (as if they were wordpress pages) without it altering the design of the site. 

Questions:
- Can there be more than six of them added without altering the layout of the site?
  ----Subquestion: should there ever be more than six?

**Comment by luetkemj** [comment]
You can rearrange as needed and have as many or as few as you need. When you get more than size it will just create a second row centered below the first.
