### ISSUE TITLE
Redo brackground images

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/mcdc#14]
old functionality won't work anymore.

use backstretch for a single bg image that does teh job

**Comment by headcomic** [comment]
There should be a BG that is black and white to match the designs in the "Graphics" folder.

**Comment by luetkemj** [comment]
Ahh this is all set - you can add it in the theme options menu.

**Comment by headcomic** [comment]
How big does the image have to be? Tried to upload it and it says it is set as the BG, but it isn't showing up when I look at the site. I am guessing it has to do with the image size.

**Comment by luetkemj** [comment]
Make sure you are doing here:

![screen shot 2015-01-08 at 4 06 14 pm](https://cloud.githubusercontent.com/assets/925980/5670709/44d21934-9750-11e4-904b-e50ca2d6ee52.png)

**Comment by headcomic** [comment]
Ahhhhhhh - fixed it. Beautiful.
