### ISSUE TITLE
Makers Page

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#15]
On the "Makers" page is there a way we can link to all the authors/makers that have ever published content on the site as opposed to just the 13 or so we currently have up there?

**Comment by luetkemj** [comment]
Yes! You need to have last names specified for them to get sorted properly. They won't show up with out a last name.

![screen shot 2015-01-08 at 3 30 24 pm](https://cloud.githubusercontent.com/assets/925980/5670186/bca34280-974b-11e4-8734-3dcad444a31d.png)

Also fixed a bug that prevented more than 10 from showing at a time

**Comment by luetkemj** [comment]
As a note - that name field is required. You won't actually able to save a maker without filling it out.

**Comment by headcomic** [comment]
Wierd. Ok, I will fix this. -Patrick

**Comment by luetkemj** [comment]
It's because we want to order by last name and the title field is a single entry only able to be ordered by the first name.

If they don't have the last name filled out they don't get output cause they can't be ordered properly.

**Comment by headcomic** [comment]
Fixed all of these
