### ISSUE TITLE
Footer Styling

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#16]
I added all of the footer links, currently they all link back to the home page. Is there any way the footer styling can more resemble the font styling in the photoshop design files? (Spaces between columns tighter, font a little smaller, etc)

**Comment by luetkemj** [comment]
yep - can do. Will probably focus more on functionality at the moment - but yes I will honor your styles.

**Comment by headcomic** [comment]
No worries! I am not anal or anything. I trust your instincts. Was it the right thing to do to place this here?

**Comment by headcomic** [comment]
I think this one is closed.
