### ISSUE TITLE
Seravek webfont

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/mcdc#17]
@headcomic

Do you have a webfont version of this? Do we have a license for it? Otherwise we need to get something else.

**Comment by headcomic** [comment]
I do not. It looks like it came with my computer somehow. We can replace it with another font. 

How about Lato? https://www.google.com/fonts#QuickUsePlace:quickUse/Family:Lato

**Comment by luetkemj** [comment]
can do

**Comment by luetkemj** [comment]
Swapped all fonts for Lato. Will need to type massage later but for now we are good to go.
