### ISSUE TITLE
p2 New Footer

### ISSUE THREAD

**Issue by luetkemj** [luetkemj/mcdc#2]
Get the new footer from the designs

This will be widget based. After launch we will ned to start getting the widgets filled out. Likely these will be menu lists so we could get those setup beforehand.

Footer menu #1, Footer Menu #2 etc...

**Comment by luetkemj** [comment]
All set on this front

**Comment by headcomic** [comment]
Make sure that you add the site credits for "Site Design by Mark Luetke & Patrick Yurick" and you can do the "Developed by Mark Luetke" credit down there if you want to as well. Those should have links to our respective sites. 

For me http://www.theheadcomic.com

**Comment by luetkemj** [comment]
opening new ticket
