### ISSUE TITLE
Some corrections for the "Features" pages

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#24]
Some notes on fixes:
![d1_feature_page_notes](https://cloud.githubusercontent.com/assets/6733647/5917273/d2648630-a612-11e4-80e8-0e7b10285c6a.png)

Revised version:*
![d1_feature_page_revised](https://cloud.githubusercontent.com/assets/6733647/5917274/d26c582e-a612-11e4-80b7-acac692fa3d6.png)

*As a bonus to this one, I kind of like the slimmer version of the header bar. That might be easily achieved by changing the proportions of the header image.

**Comment by luetkemj** [comment]
Image size/proportion is dependent on the image. So yeah, slimmer banner can be achieved with a different pic.

**Comment by luetkemj** [comment]
Re the empty space there - "what's going on here"

Resize the browser, you will see that the space changes proportionally as the screen gets smaller. The nature of a responsive web. We no longer have the luxury of pixel perfect designs because there is no longer a perfect pixel.

**Comment by headcomic** [comment]
Is this what it is supposed to do when I shrink the window?
![screen shot 2015-01-28 at 16 09 05](https://cloud.githubusercontent.com/assets/6733647/5941317/1c3ed7d8-a708-11e4-9d3c-9030af95fdf1.png)

**Comment by luetkemj** [comment]
Nope - haven't dealt with mobile on that. Will fix that.

**Comment by luetkemj** [comment]
All fixed up

**Comment by headcomic** [comment]
That space between the header bar and the items underneath still needs to be made a little more even with the spaces around it. 

I do like the slimmer header image. I will keep those proportions for the other pages as well.
