### ISSUE TITLE
Undedogs Page Mod

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#26]
I think this modification would only be for the Underdogs page, though I can see it being valuable on other pages as well. What do you think?
![underdogmod](https://cloud.githubusercontent.com/assets/6733647/5942180/e7aba8ec-a70d-11e4-91a5-392305fb0597.jpg)

**Comment by luetkemj** [comment]
Oh yeah, we can do that. Will add

**Comment by headcomic** [comment]
ok, thanks. I was just about to say, if it is easier, we can just have a second image for all of the feature pages. I can design that square to show info as a .jpeg instead of having to worry about editable text.

**Comment by luetkemj** [comment]
yep, that's what I was thinking, another field for feature pages

**Comment by headcomic** [comment]
Another feature page issue: Can we make sure that there is an equal space between the bottom of the sidebar and the footer as there is space between the header and the sidebar?
![screen shot 2015-02-11 at 10 32 21](https://cloud.githubusercontent.com/assets/6733647/6145409/6c615764-b1d9-11e4-9e6b-b25c56f5b252.png)

**Comment by luetkemj** [comment]
are we gonna need a link for those spotlight comics?

**Comment by headcomic** [comment]
Yes, good catch. I didn't think of that.

**Comment by headcomic** [comment]
The second image, where the feature is, currently expands to fill an area that is bigger than it needs to be (which is bigger than the 126 height size of the banner to the left) When you resize it can you let me know what the dimensions of both fill areas are exactly so I can create templates accordingly for all of the feature sections? Thx!

![screen shot 2015-02-13 at 10 28 11](https://cloud.githubusercontent.com/assets/6733647/6185864/0fe8de2e-b36b-11e4-89c9-d548d1e92ab9.png)

**Comment by headcomic** [comment]
I figured out the dimensions needed for that second image: 310px x 122px right?

**Comment by luetkemj** [comment]
Looks good to me.
