### ISSUE TITLE
MakingComicsWorldwide.com Feature Widget

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#28]
So I was going through and adding all of the feature squares (with the new orange, black, and white redesigns) and I noticed that they could only link to existing pages within the site. Is there any way that the Making Comics Worldwide square could link to MakingComicsWorldwide.com and open in a new tab? (as opposed to a subpage of MakingComics.com) 

![screen shot 2015-02-11 at 01 01 51](https://cloud.githubusercontent.com/assets/6733647/6139945/a8abb872-b189-11e4-82cc-9f07043d99b4.png)

**Comment by luetkemj** [comment]
ahh yeah we can do that

**Comment by luetkemj** [comment]
Done - moved the features option under the home page - makes more sense.
