### ISSUE TITLE
Can we have the ability to suppress titles on certain pages? 

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#30]
I added the comic365 page, but the default template lists the title of the page (which I don't want it to when ON the actual page). Does that make sense?

**Comment by luetkemj** [comment]
yeah I can tweak those setting so we have a choice

**Comment by luetkemj** [comment]
On pages with the default template there is a checkbox for showing the title. Default is to show. Just uncheck and it will go away.
