### ISSUE TITLE
Key Icons On Link List Pages

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#32]
So on the link list pages I would like to be able to add in little icons next to the individual lines of text. It doesn't need to be too pretty, but I would prefer to add them in line next to the entries. I am thinking of adding little symbols next to individual links (Number ratings, MC logo, $ sign, etc.) 

I am guessing this is a font style issue relating to how the P tag is interacting with images. But I wanted to see what you thought we should do to fix it. 

Check out this page to see what I'm talking about: http://www.makingcomics.com/rd/characters/

**Comment by luetkemj** [comment]
What is the problem here? They look to be inline like you want yes?

**Comment by headcomic** [comment]
Yeah, sorry. The icons on the pages are correct - the ones in the upper right corners. I am talking about the ones in like with the text. In the page link I attached to this I am talking about the little "MC" logo next to the line: "Character Design (For Your Portfolio)"

see how it indents considerably away from the MC? I "need" them to sit next to each other fluidly. I wanted to be able to add a "Key" box into the third column and have little images appended to entries that indicated the content. I am open to suggestions on this solve. It may be something we have to wait until a little later for (as I have no idea how complicated of a fix it would be) but I wanted you to be aware of it's necessity. 

![linklistkeyelements](https://cloud.githubusercontent.com/assets/6733647/6172059/76949572-b2d6-11e4-909e-ea5da2684ee8.jpg)

**Comment by luetkemj** [comment]
Do you know all of the key elements? We can use a short code for this. would look something like 

```
[legend icons="mc, v, d"]
```

I can parse thatin the backend and spit out your icons but I need to know what they will be before hand.

**Comment by headcomic** [comment]
That's a good call, I will get them right now...

Icons (That I can think of right now)

![mc](https://cloud.githubusercontent.com/assets/6733647/6172589/c35a99e4-b2d9-11e4-930a-81aae687f5ae.jpg)
- MakingComics.com Articles

![video](https://cloud.githubusercontent.com/assets/6733647/6172595/ca1d8e62-b2d9-11e4-92b9-d2def7448d8f.jpg)
- Videos

![download](https://cloud.githubusercontent.com/assets/6733647/6172598/d102f21c-b2d9-11e4-82f6-8ce0b8c50c9f.jpg)
- Downloads

![costs-something](https://cloud.githubusercontent.com/assets/6733647/6172604/d88dfac2-b2d9-11e4-9753-132d08a0c0d6.jpg)
- Costs Money, this is the only one I think we might expand upon in the future, but I don't think we should yet. My original description broke these down into even smaller sub-categories, but I think they may be confusing: "When you come across an item that costs money to the user indicate this by either adding a "$" symbol for items that just cost straight cash, "Freemium" for items that offer some services for free and others for money, "Try B4 Buy" for items that have trial offers before purchasing, "Free & Pay" for resources that include both, and leave items that cost "$0" blank. If an item says "0+" it means pay what you want with encouraged donation."

![rating1](https://cloud.githubusercontent.com/assets/6733647/6172607/decc3f70-b2d9-11e4-80c9-4628286fcc11.jpg)
- This is a relevant link, but not directly useful to the comic creation process

![rating2](https://cloud.githubusercontent.com/assets/6733647/6172615/e41556f6-b2d9-11e4-84a6-78b01366f702.jpg)
- This is a useful link, but not a high priority to know when creating comics

![rating3](https://cloud.githubusercontent.com/assets/6733647/6172624/e8bb7eba-b2d9-11e4-9750-b4ab3def08dd.jpg)
- This is a useful link with many great applications to the creation process

![rating4](https://cloud.githubusercontent.com/assets/6733647/6172628/ef70a820-b2d9-11e4-9e54-ff6a9d579ddc.jpg)
- This tool is vital to the comic creation process

**Comment by headcomic** [comment]
I just caught two more that need to be in there:

![article](https://cloud.githubusercontent.com/assets/6733647/6173019/a7888bc4-b2dc-11e4-8aeb-5d4b14b3619b.jpg)
- Article or Opinion Piece

![tutorial](https://cloud.githubusercontent.com/assets/6733647/6173025/b0ad8092-b2dc-11e4-8937-99f0118d0c4a.jpg)
-Tutorial

**Comment by luetkemj** [comment]
Alright - so I have the shortcode ready to go but I need different images. Can you get me those icons all as .png at the current and at exactly double that size? Double size is for retina screens. Once I get those I can just dump them in and we should be just about ready to go with it

**Comment by luetkemj** [comment]
FYI it's gonna look like this:
comma seperated values, no spaces
possible values: mc,a,d,t,v,s,1,2,3,4

```
[legend keys="mc,v,d"]
```

**Comment by headcomic** [comment]
How are you so awesome?
![articles](https://cloud.githubusercontent.com/assets/6733647/6174167/fff2a9fe-b2e4-11e4-8209-f327aee8a0b9.png)
![costs-something](https://cloud.githubusercontent.com/assets/6733647/6174166/fff29a7c-b2e4-11e4-8e98-5407ac3840ef.png)
![download](https://cloud.githubusercontent.com/assets/6733647/6174171/fff4c572-b2e4-11e4-9ead-8136044d692a.png)
![mc](https://cloud.githubusercontent.com/assets/6733647/6174169/fff4cca2-b2e4-11e4-8c1c-0784bafe7930.png)
![rating1](https://cloud.githubusercontent.com/assets/6733647/6174168/fff2b53e-b2e4-11e4-8a49-7ea46ea8a273.png)
![rating2](https://cloud.githubusercontent.com/assets/6733647/6174170/fff4f7f4-b2e4-11e4-8c3d-b18c97cd2dc7.png)
![rating3](https://cloud.githubusercontent.com/assets/6733647/6174174/00079850-b2e5-11e4-95aa-314f0ab20340.png)
![rating4](https://cloud.githubusercontent.com/assets/6733647/6174175/0007f534-b2e5-11e4-9f07-9deceb5cf797.png)
![tutorial](https://cloud.githubusercontent.com/assets/6733647/6174173/0006e040-b2e5-11e4-9058-43a0e2825438.png)
![video](https://cloud.githubusercontent.com/assets/6733647/6174172/0006ec7a-b2e5-11e4-997a-34a2f0d6d8f7.png)

**Comment by luetkemj** [comment]
Sweet! It's working I see you are already using it. lemme know if you have any qs.

Also remember that for "$" we use an "s"

**Comment by luetkemj** [comment]
Also adding more down the road is pretty trivial. Just need to get the icons from you in the right size and format

**Comment by headcomic** [comment]
You are too fucking cool.

Patrick Yurick
@patrickyurick https://twitter.com/patrickyurick
theHeadcomic.com http://theheadcomic.com/
_USA:_ (619) 727-8396
*UK: *+44 07429999565

_CEO_ Making Comics Worldwide http://makingcomics.com/
_Instructor_ HTHMOOCS.org http://hthmoocs.org/
_Creator_ Thrillbent.com http://thrillbent.com/
_Creator_  Head Comics http://www.gocomics.com/head-comics
_Art Director_ Spikeandreggie.com http://spikeandreggie.com/
_Lead Illustrator_ Buzzfarmers.com http://buzzfarmers.com/

**Comment by luetkemj** [comment]
Oh, and the order doesn't matter. But it will respect your order. So you could do 4,mc,t if you wanted to for whatever reason
 should probably decide on a set order to work from for consistency

**Comment by headcomic** [comment]
One last thing here. The line space between submit, edit, and the key is really big. Is there an easy way to change the distance between the image elements?

![screen shot 2015-02-12 at 21 41 19](https://cloud.githubusercontent.com/assets/6733647/6177609/f28f00a8-b2ff-11e4-8e1b-0e4ceb9bdf27.png)

**Comment by headcomic** [comment]
New icons:

![1](https://cloud.githubusercontent.com/assets/6733647/6314056/ec5d007a-b9c3-11e4-985d-cfcccd729371.png)

![2](https://cloud.githubusercontent.com/assets/6733647/6314058/f150567c-b9c3-11e4-9636-9b7e3956d868.png)

![3](https://cloud.githubusercontent.com/assets/6733647/6314060/0c3fa6e0-b9c4-11e4-912a-2c2468b12723.png)

![4](https://cloud.githubusercontent.com/assets/6733647/6314061/110df956-b9c4-11e4-98a3-283780d3e3e3.png)

**Comment by headcomic** [comment]
Don't know how to reopen this - the last two points are issues still. -P

**Comment by luetkemj** [comment]
Word, will reppen

+++++++++++++++++++++++++
Mark Luetke
Associate Director of Web Development – VCUarts
325 N Harrison Street, Room 227
luetkemj@vcu.edu
