### ISSUE TITLE
Link List Page Descriptions

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#33]
I kind of want your opinion on this before implementing. I was thinking that it might (might) be beneficial to add an area next to the icons on the link list pages that describes what the page content is covering. Now, this could be done in column 1 or 3 as well. I am worried that it might be too cluttered with the description, but I want another pair of eyes on it before we decided whether or not to implement. 

![screen-shot-2015-02-11-at-19 37 37](https://cloud.githubusercontent.com/assets/6733647/6154778/3eb785c0-b226-11e4-98b6-92b2c239982b.jpg)

**Comment by luetkemj** [comment]
Proposed solution - this is a bit of redesign to the header section but I think it's more clear in practice.

![screen shot 2015-02-12 at 12 03 04 pm](https://cloud.githubusercontent.com/assets/925980/6172487/259a7bae-b2af-11e4-9fc5-2775644c42b4.png)

**Comment by headcomic** [comment]
Looks gorgeous, let's do it.

**Comment by headcomic** [comment]
@luetkemj can we change these to lowercase except for first letter? the block text is a bit hard to read on the longer description.

**Comment by luetkemj** [comment]
done
