### ISSUE TITLE
Content Guide Repeat of Front Page Flow

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#36]
So I am working a bit on the "Content Guide" section of the site: http://www.makingcomics.com/rd/content-guide/

At the bottom of this page where I am going to list more detailed descriptions of each of the sections on the front page, I am wondering if there is a way to just completely duplicate the information on the front page of the site (3 columns under Making, Distribution, and More, with all of the icons for the modules) on this page as well with added room underneath each for descriptions of that section... lemme know :)

**Comment by luetkemj** [comment]
All set. Added description field which doubles for the description editor on the module page itself

**Comment by headcomic** [comment]
@luetkemj these aren't showing up for all of them in the content guide...
