### ISSUE TITLE
Notes on pages within dashboard

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#41]
Is there anyway we can include notes on the module pages that we can leave for each other when editing in the dashboard? Something that will not show up on the page display, but just are general notes.

For instance - The module page "Exemplars" has different rules for laying out entries than say the "Conventions" (Take a look). I would love to be able to leave notes about the rules for entering information in those pages so that if someone else is editing they know why information is in certain places.

**Comment by luetkemj** [comment]
Not fixing this for now. Waiting till after the new sorty mc-sortingstons get sorted. Then if it is still an issue we can reopen.
