### ISSUE TITLE
TalkingComics specific page sidebar issue

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#42]
I am perplexed about how to do this, but Kevin and I want to add a #talkingcomics only twitter feed in the sidebar of the talkingcomics feature page. I tried to embed the widget, but it is autoformatting and overflowing out of the sidebar. Wondering if you could take a look and see if there is a fix.

**Comment by luetkemj** [comment]
Not sure about this one - they have a min-width inline style embedded via JS - not sure we can override that...

**Comment by headcomic** [comment]
This is resolved
