### ISSUE TITLE
Content Guide module pages descriptions aren't all loading

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#43]
They just ain't showin' up yo.

**Comment by luetkemj** [comment]
Link to a page with this problem? Thinking this might be a cache issue. If not I need a link to see what's wrong

**Comment by headcomic** [comment]
Does this make more sense? List at - http://www.makingcomics.com/rd/content-guide/
![screen-shot-2015-03-16-at-13 59 00](https://cloud.githubusercontent.com/assets/6733647/6667612/20fd09f0-cbe5-11e4-8086-0de76e96dc57.jpg)

**Comment by luetkemj** [comment]
Ahhhhhhhh - yes that makes much more sense. Will fix

**Comment by headcomic** [comment]
This still needs fixing

**Comment by luetkemj** [comment]
FIXED!
