### ISSUE TITLE
Module page descriptions

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#50]
![screen shot 2015-03-08 at 17 47 23](https://cloud.githubusercontent.com/assets/6733647/6546832/40066fc4-c5bb-11e4-9a56-4845a06002b1.png)

**Comment by headcomic** [comment]
This is in reference to the all caps being the default styling on the module page descriptions on the actually module pages ( i.e. http://www.makingcomics.com/rd/brainstorming/) 

instead of the description reading: 

RESOURCES INTENDED FOR THE BEGINNING STAGES OF COMIC CREATION AND ARE FOR THOUGHT GENERATION AND PRELIMINARY ORGANIZATION.

it would read:

Resources intended for the beginning stages of comic creation and are for thought generation and preliminary organization.

**Comment by luetkemj** [comment]
Removed text transform on these. It will respect whatever case you input it as.
