### ISSUE TITLE
WebcomicUnderdogs.com merging comments question

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#54]
Basically, Kevin and I, unaware of the process we were going to go through to simply import the Underdogs.com content, actually reformated and posted some of the underdogs content on MakingComics.com already.

For instance the article "DIY: Cutting Out The Middle Man" appears in two places:
1. http://www.webcomicunderdogs.com/d-y-i-comics-cutting-out-the-middle-man-by-jessie-w-craig/
2. http://www.makingcomics.com/rd/2014/11/24/d-i-y-comics-cutting-middle-man/

The question is, can we use the plugin (http://www.webmastertools.bz/move-wordpress-comments-to-different-website-or-post/) to take the comments from post #1 and import them onto the already "MakingComics.com" formatted article #2 ?

**Comment by luetkemj** [comment]
That look slike manual DB manipulation which sounds like we'd be in for a world of hurt in teh long run.

If you ask me I would just do a stand export of all posts from underdogs. Then do a stand import to MCDC. This will include all comments. After everything is in you can do your reformatting as needed.

**Comment by headcomic** [comment]
Ok, I will relay this as the workflow to Marisa and Michael.

**Comment by headcomic** [comment]
This is resolved
