### ISSUE TITLE
Why isn't this link showing up in search results?

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#55]
![screen shot 2015-03-17 at 09 27 53](https://cloud.githubusercontent.com/assets/6733647/6684309/0047a780-cc88-11e4-9a81-13a2949105d6.png)
![screen shot 2015-03-17 at 09 28 01](https://cloud.githubusercontent.com/assets/6733647/6684311/051280aa-cc88-11e4-8fbf-604b258a78ab.png)

**Comment by luetkemj** [comment]
The admin shows something in "Writing"

The front end is in Branding

Unless I am missing something that would seem to be the problem
