### ISSUE TITLE
Tagline Implementation

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#60]
Add this tagline graphic to the site:

![taggraphic](https://cloud.githubusercontent.com/assets/6733647/7632893/cac4782e-fa48-11e4-8f1c-a4b527eb1c97.png)

So that it looks like:

![screen shot 2015-05-14 at 14 29 14](https://cloud.githubusercontent.com/assets/6733647/7632900/d617096c-fa48-11e4-9c93-44194758fafd.png)

**Comment by luetkemj** [comment]
I need a double res version of this for retina

**Comment by headcomic** [comment]
Ok, will get to you asap - it is the google font "reenie beanie" if you
want to do it before I am on my computer next.

**Comment by luetkemj** [comment]
I don't have the font and it's not vector so I can't double it myself. Otherwise I would.

**Comment by luetkemj** [comment]
Oh... Read that as the color reenie beanie... Not that that means anything... 

Mark Luetke

**Comment by headcomic** [comment]
Ok, no worries I'll send it soon

**Comment by luetkemj** [comment]
Don't worry about it - I can grab the font and take care of it. No image needed.

**Comment by headcomic** [comment]
Can you center the header & tagline?

---

Patrick Yurick
@patrickyurick https://twitter.com/patrickyurick
theHeadcomic.com http://theheadcomic.com/
_USA:_ (619) 727-8396
*UK: *+44 07429999565

_Chief Executive Officer_ Making Comics Worldwide http://makingcomics.com/

_Lead of MOOC Design & Instruction *High Tech High GSE
http://www.hightechhigh.org/moocs/
*Creator_  Hipster-Picnic.com http://hipster-picnic.com/
