### ISSUE TITLE
Login issue on underdogforums.makingcomics.com

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#62]
(From Marisa)
Hey guys - looks like there's a login issue going on. When a member tries to retrieve their forgotten password, they get this error:

The e-mail could not be sent.
Possible reason: your host may have disabled the mail() function.
We've experienced this in the past before, and it had to do with the sending email address, which needs to be "wordpress@yourdomain.com". Right now (under Advanced Email Options) it's sending as "contact@underdogforums.makingcomics.com". I believe you'll need to create a new domain-based address, which would be "wordpress@underdogforums.makingcomics.com". Once you do that, I can change the advanced email option settings and we should be good.

**Comment by luetkemj** [comment]
wordpress@underdogforums.makingcomics.com has been created

**Comment by headcomic** [comment]
Was this all straightened out?

**Comment by luetkemj** [comment]
Almost. Still need to tweak the from email but yes things seem to be working according to marisa.

Mark Luetke
Associate Director of Web Development – VCUarts
325 N Harrison Street, Room 227
luetkemj@vcu.edu
