### ISSUE TITLE
"Exemplars" page not loading properly...

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#68]
http://www.makingcomics.com/exemplars/

For some reason it is stuck on the loading screen

**Comment by luetkemj** [comment]
hmmm... only page to do that. Feed exists and is accessable. Maybe it's too large? It's over twice the size of the others...

Investigating

**Comment by luetkemj** [comment]
This is a weird bug. I got it to work at a limit of 86 posts. Beyond that the feed fires a 500 error. There is some discussion about this bug on github. Hopefully it will eventually resolve.

**Comment by headcomic** [comment]
Ok, interesting. I will make a note not to add more than 86 to a module until you give me the go ahead.

**Comment by luetkemj** [comment]
some clues: 

https://github.com/WP-API/WP-API/issues/475

**Comment by headcomic** [comment]
So is it a result of the title being too long?

---

Patrick Yurick
@patrickyurick https://twitter.com/patrickyurick
theHeadcomic.com http://theheadcomic.com/
_USA:_ (619) 727-8396
*UK: *+44 07429999565

_Chief Executive Officer_ Making Comics Worldwide http://makingcomics.com/

_Lead of MOOC Design & Instruction *High Tech High GSE
http://www.hightechhigh.org/moocs/
*Creator_  Hipster-Picnic.com http://hipster-picnic.com/

**Comment by luetkemj** [comment]
No this is an internal wp-json bug. They are aware and working on a fix. Looks like there may be a tweak to the plugin that could temporarily fix it for us. But I need some coffee before I try it...

![giphy-1](https://cloud.githubusercontent.com/assets/925980/7783655/0ae93c08-0117-11e5-90d1-071fc074be1c.gif)

**Comment by headcomic** [comment]
Ahh the old "Osmosis" drinking method. I support.

---

Patrick Yurick
@patrickyurick https://twitter.com/patrickyurick
theHeadcomic.com http://theheadcomic.com/
_USA:_ (619) 727-8396
*UK: *+44 07429999565

_Chief Executive Officer_ Making Comics Worldwide http://makingcomics.com/

_Lead of MOOC Design & Instruction *High Tech High GSE
http://www.hightechhigh.org/moocs/
*Creator_  Hipster-Picnic.com http://hipster-picnic.com/

**Comment by luetkemj** [comment]
Should be fixed for now but we need to keep an eye in this one to make sure. Also if we update wp-api we need to check and see if the problem persists as I hacked the plugin to fix it. They should be working on a solution those as it's def on their radar
