### ISSUE TITLE
"Podcasts & Audio" not found in "Add New Resource"

### ISSUE THREAD

**Issue by headcomic** [luetkemj/mcdc#69]
When I go to add a new resource the option for "Podcasts & Audio" isn't showing up, just the option for "Podcasts". I am guessing it just didn't auto switch when we updated the module. Something I can fix?

![podcasts](https://cloud.githubusercontent.com/assets/6733647/7787508/2590a964-0208-11e5-9454-9a1055b38e18.jpg)

**Comment by luetkemj** [comment]
Yeah, we updated the page name for the module not the name of the module itself. It's fixed now.
